apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: default
  labels:
    app: payment
    tier: app
    project: roboshop
spec:
  replicas: {{ .Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app: payment
      tier: app
      project: roboshop
  template:
    metadata:
      name: payment
      labels:
        app: payment
        tier: app
        project: roboshop
    spec:
      containers:
      - name: payment
        image: "parasuramkoppada/payment:{{ .Values.deployment.imageVersion}}"