apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
    tier: DB
    project: roboshop
spec:
  replicas: {{ .Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app: mongodb
      tier: DB
      project: roboshop
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
        tier: DB
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: "parasuramkoppada/mongodb:{{ .Values.deployment.imageVersion}}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi

