apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
    tier: DB
    project: roboshop
spec:
  clusterIP: None
  selector:
    # you should provide pod labels here
    app: mysql
    tier: DB
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    # service port
    port: '{{ .Values.service.servicePort}}'
    # pod port
    targetPort: '{{ .Values.service.targetPort}}'
