apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
    tier: DB
    project: roboshop
spec:
  clusterIP: None
  selector:
    # you should provide pod labels here
    app: redis
    tier: DB
    project: roboshop
  ports:
  - name: redis-port
    protocol: TCP
    # service port
    port: "{{ .Values.service.servicePort}}"
    # pod port
    targetPort: "{{ .Values.service.targetPort}}"
