apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
    tier: DB
    project: roboshop
spec:
  replicas: {{ .Values.deployment.reclicaCount}}
  selector:
    matchLabels:
      app: redis
      tier: DB
      project: roboshop
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tier: DB
        project: roboshop
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi

