apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
  labels:
    app: web
    tier: web
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    # you should provide pod labels here
    app: web
    tier: web
    project: roboshop
  ports:
  - name: web-port
    protocol: TCP
    # service port
    port: {{ .Values.service.servicePort}}
    # pod port
    targetPort: {{ .Values.service.targetPort}}