apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app: rabbitmq
    tier: DB
    project: roboshop
spec:
  clusterIP: None
  selector:
    # you should provide pod labels here
    app: rabbitmq
    tier: DB
    project: roboshop
  ports:
  - name: rabbitmq-amq
    protocol: TCP
    # service port
    port: {{ .Values.service.amqservicePot}}
    # pod port
    targetPort: {{ .Values.service.amqtargetPort}}
  - name: rabbitmq-http
    protocol: TCP
    # service port
    port: {{ .Values.service.httpservicePort}}
    # pod port
    targetPort: {{ .Values.service.httptargetPort}}
