apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app: rabbitmq
    tier: DB
    project: roboshop
spec:
  replicas: {{ .Values.deployment.reclicaCount}}
  selector:
    matchLabels:
      app: rabbitmq
      tier: DB
      project: roboshop
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
        tier: DB
        project: roboshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
