apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: default
  labels:
    app: catalogue
    tier: app
    project: roboshop
spec:
  selector:
    # you should provide pod labels here
    app: catalogue
    tier: app
    project: roboshop
  ports:
  - name: catalogue-port
    protocol: TCP
    # service port
    port: {{ .Values.service.servicePort}}
    # pod port
    targetPort: {{.Values.service.targetPort}}