apiVersion: v1 #(required) this is the version of k8 api-resource
name: web #(required) this is the chart name
version: 1.0.0 #(required) this is the version of chart
description: this is the web helm chart #(optional)
appVersion: v1.0.0 # this is the version of application not manifest
